### ISSUE TITLE
Simple Front End UI

### ISSUE THREAD

**Issue by pvgupta24** [WebClub-NITK/Hacktoberfest-2k17#10]
### Simple Front End UI
* Create a folder named "Front_End_UI". 
* Make a subfolder with your github-handle as the name
 For example mine would be pvgupta24

 #### Make an index.html and implement
 - [ ] Navbar with a dropdown, logo, few links for sections (or Sidebar)
 - [ ] A section with an image and some text.
 - [ ] A section with a simple form (including text fields, radiobuttons, buttons etc) 
Note : No backend required
 - [ ] A footer with your details and link to your github handle.

##### Note : 
* You can use UI Frameworks or just plain CSS and JavaScript.
* Make sure your Pull Requests have just one commit in them.
Squash multiple commits into one if you have to.
> Look up the CONTRIBUTING.md document to see how to push your code to GitHub.

**Comment by immanojab** [comment]
I claim

**Comment by illseption** [comment]
Can I try this?

**Comment by pvgupta24** [comment]
@illseption  go ahead.

**Comment by abhilash97** [comment]
Can I work on this?

**Comment by abhilash97** [comment]
Can i work on this issue?

**Comment by immanojab** [comment]
Yes u can

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
