### ISSUE TITLE
Add Happy Hacking in any Esoteric programming language

### ISSUE THREAD

**Issue by omkarprabhu-98** [WebClub-NITK/Hacktoberfest-2k17#12]
* To know about esoteric programming languages refer:  [Weird Languages](https://en.wikipedia.org/wiki/Esoteric_programming_language)
1.  Make a new folder called  **Happy_Hacking**
2.  In that folder add a markdown file called  `<github-handle>.md` 
For example mine would be `omkarprabhu-98.md`
3. Write the code for printing **Happy Hacking!** in the md file in any esoteric language

Look up the CONTRIBUTING.md document to see how to push your code to GitHub.

**Comment by darioTecchia** [comment]
Check my PR #349

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
