### ISSUE TITLE
Add Insertion Sort

### ISSUE THREAD

**Issue by rahulsnkr** [WebClub-NITK/Hacktoberfest-2k17#13]
- Refer to [this](https://en.wikipedia.org/wiki/Insertion_sort#Algorithm_for_insertion_sort) page to read about insertion sort.

- Create a folder named "Insertion_Sort". Within that folder, add a file called `<github-handle>.c`. For example, mine would be `rahulsnkr.c`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by Feynman3142** [comment]
I claim

**Comment by crp987654321** [comment]
I claim

**Comment by prashantagno3** [comment]
i claim

**Comment by AkshaySharma-Akay** [comment]
I Claim!

**Comment by hardikran** [comment]
i claim

**Comment by adarshj17** [comment]
I Claim!

**Comment by Rakeshpavan333** [comment]
i claim

**Comment by geekgeekvm** [comment]
i claim

**Comment by isunitha98selvan** [comment]
I claim!

**Comment by ashwathbhat** [comment]
I claim!

**Comment by mvibhamenon** [comment]
I claim

**Comment by shivampotdar99** [comment]
i claim!!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
