### ISSUE TITLE
Make a simple profile card using HTML and CSS

### ISSUE THREAD

**Issue by anumehaagrawal** [WebClub-NITK/Hacktoberfest-2k17#14]
1. Create a folder named "Profile_Card"
2. Make a subfolder with your github-handle as the name .For example mine would be anumehaagrawal

In a file named index.html , create a profile card with image of the person , name , contact number and links to facebook , gmail and github.

     

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by crp987654321** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
