### ISSUE TITLE
Implement Sieve of Erastothenes

### ISSUE THREAD

**Issue by utkarsh23** [WebClub-NITK/Hacktoberfest-2k17#17]
![Sieve of Erastothenes](https://upload.wikimedia.org/wikipedia/commons/b/b9/Sieve_of_Eratosthenes_animation.gif)
* Lookup the ancient prime sieve algorithm [Sieve of Erastothenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) 
* Create a folder with your github username (mine would be "utkarsh23").
* In this folder create a file called "sieve_of_erastothenes" and write your implementation of Sieve of Erastothenes in any language of your choice (Python preferably since implementation is quite easy).

Refer to [CONTRIBUTING.md](https://github.com/WebClub-NITK/Hacktoberfest-2k17/blob/master/CONTRIBUTING.md) and stick to these contribution guidelines.

**Comment by PSL14** [comment]
I claim!

**Comment by ankitgaur17** [comment]
I claim!

**Comment by geekgeekvm** [comment]
i claim!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
