### ISSUE TITLE
Add Fibonacci Search

### ISSUE THREAD

**Issue by rahulsnkr** [WebClub-NITK/Hacktoberfest-2k17#19]
- Refer to [this](https://en.wikipedia.org/wiki/Fibonacci_search_technique) page to read about fibonacci search.

- Create a folder named "Fibonacci_Search". Within that folder, add a file called `<github-handle>`.c. For example, mine would be rahulsnkr.c

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by archit-p** [comment]
I claim this issue

**Comment by NJnisarg** [comment]
I came

**Comment by RosaGeorge31** [comment]
I claim

**Comment by isunitha98selvan** [comment]
I claim

**Comment by ankitsvt11** [comment]
i claim

**Comment by crp987654321** [comment]
I claim

**Comment by hardikran** [comment]
I claim

**Comment by ianjathanna** [comment]
I claim

**Comment by Feynman3142** [comment]
I claim

**Comment by ianjathanna** [comment]
I claim!

**Comment by failedcoder12** [comment]
I claim

**Comment by geekgeekvm** [comment]
i claim!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
