### ISSUE TITLE
Implement Simple Hello World Page

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#22]
* Implement a simple webpage with a button. On clicking the button, "Hello World" should be displayed on the page. (Include the javascript within the same file, in `<script>` tags)
* For HTML and Javascript reference, visit [W3Schools](https://www.w3schools.com/default.asp)
* Create a folder named `Hello_Web`. In that folder add a file called `<github-handle>.html`
For example mine would be `MJ10.html`

**Comment by chaitany10** [comment]
i claim

**Comment by karanmohadikar** [comment]
i claim

**Comment by shivampotdar99** [comment]
i CLAIM!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
