### ISSUE TITLE
Add Merge Sort

### ISSUE THREAD

**Issue by rahulsnkr** [WebClub-NITK/Hacktoberfest-2k17#23]
- Refer to [this](https://en.wikipedia.org/wiki/Merge_sort#Algorithm) page to read about merge sort.

- Create a folder named "Merge_Sort". Within that folder, add a file called `<github-handle>`.c. For example, mine would be rahulsnkr.c

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by immanojab** [comment]
I claim!! :

**Comment by AkshaySharma-Akay** [comment]
I claim!

**Comment by Rakeshpavan333** [comment]
i claim

**Comment by geekgeekvm** [comment]
i claim

**Comment by mvibhamenon** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
