### ISSUE TITLE
Add Quick Sort

### ISSUE THREAD

**Issue by rahulsnkr** [WebClub-NITK/Hacktoberfest-2k17#24]
- Refer to [this](https://en.wikipedia.org/wiki/Quicksort#Algorithm) page to read about quick sort.

- Create a folder named "Quick_Sort". Within that folder, add a file called `<github-handle>`.c. For example, mine would be rahulsnkr.c

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by hlpr98** [comment]
i Claim!

**Comment by rjshubh** [comment]
i claim

**Comment by crp987654321** [comment]
I claim!

**Comment by PSL14** [comment]
I claim!

**Comment by ankitgaur17** [comment]
I claim!

**Comment by hardikran** [comment]
I claim

**Comment by Rakeshpavan333** [comment]
i claim

**Comment by geekgeekvm** [comment]
i claim!

**Comment by Feynman3142** [comment]
I claim!

**Comment by Him98** [comment]
I claim!

**Comment by RosaGeorge31** [comment]
I Claim!

**Comment by AB261** [comment]
I Claim!

**Comment by mvibhamenon** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
