### ISSUE TITLE
Add Binary Search

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#25]
* To get started, learn about Binary Search [here](https://en.wikipedia.org/wiki/Binary_search_algorithm)
* You can implement the algorithm in any language of your choice.
* Create a folder named `BinarySearch`. In that folder add a file called `<github-handle>.<extension>`
For example if I implement Binary Search in Python, it would be `MJ10.py`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by vsushruth** [comment]
I claim

**Comment by imnisarg** [comment]
I claim

**Comment by Anish1207** [comment]
I claim

**Comment by krahulreddy** [comment]
I claim

**Comment by Madhuparna04** [comment]
i claim

**Comment by prashantagno3** [comment]
i claim

**Comment by AmodhShenoy** [comment]
I claim!

**Comment by ramramki26** [comment]
I claim!

**Comment by aswanthpp** [comment]
I claim

**Comment by pramathabhat** [comment]
I claim!

**Comment by Munees11** [comment]
I claim!!

**Comment by aswanthpp** [comment]
I claim

**Comment by prathamsingh90** [comment]
i claim

**Comment by Maaaaad** [comment]
I claim

**Comment by prashantagno3** [comment]
i claim

**Comment by sajangrover** [comment]
i claim

**Comment by abhiramnair6123** [comment]
i claim

**Comment by Rakeshpavan333** [comment]
i claim

**Comment by jvsriharsha** [comment]
i claim

**Comment by sriharsha05** [comment]
i claim

**Comment by Prajnaaa12** [comment]
I claim

**Comment by AB261** [comment]
I claim!

**Comment by AB261** [comment]
I claim!

**Comment by sambhav2612** [comment]
I claim!

**Comment by GENU05** [comment]
I Claim.

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
