### ISSUE TITLE
Simple GUI Calculator

### ISSUE THREAD

**Issue by pvgupta24** [WebClub-NITK/Hacktoberfest-2k17#26]
## Simple GUI Calculator
* Make a folder named "GUI_Calculator"
* Make a subfolder with your github handle as the name.
For example mine would be pvgupta24

**Note**
* Implement in any language .
* E.g ,  in Java by using libraries like Java AWT, Java Swing, Java FX.
 Read about basics of  [Java Swing](https://www.javatpoint.com/java-swing), [Java AWT](https://www.javatpoint.com/java-awt).
* Include a README.md file with usage instructions and limitations.

> Lookup CONTRIBUTING.md document for more instructions.

**Comment by salman-bhai** [comment]
Give links to read up on Java Swing, AWT, etc....

**Comment by failedcoder12** [comment]
I Claim

**Comment by rohitkhoja** [comment]
I claim

**Comment by hlpr98** [comment]
I Claim

**Comment by srinskit** [comment]
I Claim!

**Comment by sarthakc0806** [comment]
I claim

**Comment by ashwathbhat** [comment]
I Claim

**Comment by jvsriharsha** [comment]
i claim

**Comment by abhilash97** [comment]
I would like to work on this issue.

**Comment by pragathii** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
