### ISSUE TITLE
Add Bubble Sort

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#27]
* To get started, learn about Bubble Sort [here](https://en.wikipedia.org/wiki/Bubble_sort)
* You can implement the algorithm in any language of your choice.
* Create a folder named `BubbleSort`. In that folder add a file called `<github-handle>.<extension>`
For example if I implement Bubble Sort in Python, it would be `MJ10.py`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by chaitany10** [comment]
I claim

**Comment by KrazyUchiha** [comment]
I claim

**Comment by akshitpatel01** [comment]
I claim

**Comment by span09** [comment]
I claim

**Comment by Rakeshpavan333** [comment]
I claim

**Comment by prashantagno3** [comment]
i claim

**Comment by AmodhShenoy** [comment]
I Claim!

**Comment by ramramki26** [comment]
I claim!

**Comment by sajangrover** [comment]
i claim!

**Comment by arc999** [comment]
I Claim !

**Comment by Shreyanshnit19** [comment]
I claim !

**Comment by Manask322** [comment]
I claim!

**Comment by radhe14341** [comment]
I Claim!

**Comment by ankitgaur17** [comment]
I Claim!

**Comment by AB261** [comment]
I claim

**Comment by Anish1207** [comment]
I claim

**Comment by pramathabhat** [comment]
I claim!

**Comment by SrivatsanV** [comment]
I claim!

**Comment by jvsriharsha** [comment]
i claim

**Comment by Mukesh-BR** [comment]
I Claim

**Comment by geekgeekvm** [comment]
i claim!

**Comment by sriharsha05** [comment]
i claim

**Comment by Prajnaaa12** [comment]
i claim

**Comment by mvibhamenon** [comment]
I claim

**Comment by mvibhamenon** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
