### ISSUE TITLE
BITWISE Operators

### ISSUE THREAD

**Issue by mishal23** [WebClub-NITK/Hacktoberfest-2k17#28]
- Learn about Bitwise operators from [here](https://www.tutorialspoint.com/cprogramming/c_bitwise_operators.htm)
- Implement all bitwise operators in language of your choice.
-  Create a folder ```Bitwise Operator``` if not done already.
-  Create a file with your github username, eg. ```mishal23.c``` (general _githubusername.extension_ )

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by parthsl** [comment]
I Claim!

**Comment by ArqumShaikh** [comment]
I Claim!

**Comment by pragathii** [comment]
I claim!

**Comment by patilprajwal** [comment]
i claim!

**Comment by jvsriharsha** [comment]
I claim

**Comment by kul96** [comment]
i claim

**Comment by Prajnaaa12** [comment]
I claim

**Comment by ashwathbhat** [comment]
I Claim

**Comment by Madhuparna04** [comment]
I claim !

**Comment by Z0Marlin** [comment]
i claim!

**Comment by Rakeshpavan333** [comment]
i claim

**Comment by Prajnaaa12** [comment]
I claim

**Comment by sriharsha05** [comment]
i claim

**Comment by jvsriharsha** [comment]
i claim

**Comment by Prajnaaa12** [comment]
I claim

**Comment by pragathii** [comment]
I claim!

**Comment by ShreyasheeS** [comment]
I claim.

**Comment by shivampotdar99** [comment]
i claim!!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
