### ISSUE TITLE
Create a Menu Based Calculator which takes input from the User

### ISSUE THREAD

**Issue by salman-bhai** [WebClub-NITK/Hacktoberfest-2k17#4]
All languages are welcome here! Make sure you `reference` the Issue! 
You have to create a menu-driven calculator which asks the user for the two inputs and the operand symbol. Include addition, division, multiplication and division!

## Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by anumehaagrawal** [comment]
I claim

**Comment by anumehaagrawal** [comment]
I claim

**Comment by Prajnaaa12** [comment]
I claim!

**Comment by prashantagno3** [comment]
i claim

**Comment by rohitkhoja** [comment]
i claim

**Comment by nishanthebbar2011** [comment]
I claim

**Comment by vachhanihpavan** [comment]
I claim

**Comment by prashantagno3** [comment]
i claim

**Comment by prashantagno3** [comment]
i claim

**Comment by geekgeekvm** [comment]
i claim

**Comment by mvibhamenon** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
