### ISSUE TITLE
Make a program to add two numbers in python.

### ISSUE THREAD

**Issue by kartik2000** [WebClub-NITK/Hacktoberfest-2k17#429]
I wanted to work on it.

**Comment by MJ10** [comment]
@kartik2000 Please add a proper description to the issue. You can refer to #3 to see the format.

**Comment by kartik2000** [comment]
Create a folder named python. In that folder add a file called <github-handle>.py
For example mine would be kartik.py

After adding your file make sure you delete the compiled binary executable, before pushing the file to your branch on your fork!

**Comment by NishantMR7** [comment]
# Simple Python program to Add Two Numbers
 
number1 = input(" Please Enter the First Number: ")
number2 = input(" Please Enter the second number: ")
 
# Using arithmetic + Operator to add two numbers
sum = float(number1) + float(number2)
print('The sum of {0} and {1} is {2}'.format(number1, number2, sum))

**Comment by mvibhamenon** [comment]
I claim

**Comment by Mudra01** [comment]
I claim!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
