### ISSUE TITLE
Add Bucket sort in python

### ISSUE THREAD

**Issue by praabi** [WebClub-NITK/Hacktoberfest-2k17#457]
To add a bucket sort within a range and with particular number of buckets.
It will sort the unarranged array using bucket sort within that range only.
The first line will take the input of range and the no of buckets with space in hierarchical order.
The second line will take the input of the array to be sorted.
The output will give the sorted array of given array.

* The name of the file should be your github username. For example, mine would be praabi.py
* Move it to the `Bucket_Sort` folder

Please follow the contributing guidelines when sending a PR.

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
