### ISSUE TITLE
add fibonacci in python

### ISSUE THREAD

**Issue by faisalarkan21** [WebClub-NITK/Hacktoberfest-2k17#560]
Display numbers of the Fibonacci Series up till a particular using Python. 

* Also a screenshot of your submission
* Move that directory to `Fibonacci-Python` directory.
For eg. location of my solution would be `/Fibonacci-Python/salman-bhai.py`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
