### ISSUE TITLE
Coin Sum

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#572]
* Solve Problem 31: [Coin Sum](https://projecteuler.net/problem=31) on Project Euler
* Make a directory whose name is your Github username. Move your solution to that folder. Also a screenshot of your submission.
* Move that directory to `Problem31` directory in the `ProjectEuler` directory.
For eg. location of my solution would be `/ProjectEuler/Problem31/MJ10/`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by kamerk22** [comment]
I Claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
