### ISSUE TITLE
Pandigital prime

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#573]
* Solve Problem 41: [Pandigital prime](https://projecteuler.net/problem=41) on Project Euler
* Make a directory whose name is your Github username. Move your solution to that folder. Also a screenshot of your submission.
* Move that directory to `Problem41` directory in the `ProjectEuler` directory.
For eg. location of my solution would be `/ProjectEuler/Problem41/MJ10/`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
