### ISSUE TITLE
Largest palindrome product

### ISSUE THREAD

**Issue by MJ10** [WebClub-NITK/Hacktoberfest-2k17#574]
* Solve Problem 4: [Largest palindrome product](https://projecteuler.net/problem=4) on Project Euler
* Make a directory whose name is your Github username. Move your solution to that folder. Also a screenshot of your accepted submission on ProjectEuler.
* Move that directory to `Problem4` directory in the `ProjectEuler` directory.
For eg. location of my solution would be `/ProjectEuler/Problem4/MJ10/`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

**Comment by asaaditya8** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
