### ISSUE TITLE
CRUD App

### ISSUE THREAD

**Issue by mishal23** [WebClub-NITK/Hacktoberfest-2k17#7]
- Make a CRUD app(webapp/app), which takes user personal data such as name, email, number, country

Features:
- Use a Database to store entries.
- Validate the entries.
- Edit option available.
- Open to new ideas.

**Comment by salman-bhai** [comment]
I think you should probably simplify this a bit!

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
