### ISSUE TITLE
Simple HTTP Server in Go

### ISSUE THREAD

**Issue by EkamWalia** [WebClub-NITK/Hacktoberfest-2k17#765]
Go is quickly becoming a popular choice for web developers when selecting a framework for the backend.
I believe it is a good contribution to have a Simple HTTP Server written in Golang on this repository

**Comment by EkamWalia** [comment]
I have a raised a pull request , Request #771

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
