### ISSUE TITLE
Add linked list implementations

### ISSUE THREAD

**Issue by sharanyakamath** [WebClub-NITK/Hacktoberfest-2k17#8]
Add implementations for the following in C:
1. Memory efficient double linked list (XOR linked list) 
2. Circular linked list.
3. Unrolled linked list.

- Create a folder named < github-handle >. For example mine would be sharanyakamath.
- In that folder add a files named xor.c , circular.c and unrolled.c

**Comment by salman-bhai** [comment]
Add Appropriate labels to the same!

**Comment by vachhanihpavan** [comment]
I claim

**Comment by salman-bhai** [comment]
Issue closed, end of Hacktoberfest!
